version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies with npm ci..."
      - npm ci
      - echo "Verifying Vite installation..."
      - ./node_modules/.bin/vite --version
  build:
    commands:
      - echo "Building the app..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "Syncing built files to S3 with correct MIME types..."
      # Sync all files (initial upload without MIME)
      - aws s3 sync dist/ s3://your-bucket-name/ --delete
      # Force MIME types for JS files (main culprit for module errors)
      - aws s3 cp s3://your-bucket-name/dist/assets/ s3://your-bucket-name/dist/assets/ --recursive --exclude "*" --include "*.js" --metadata-directive REPLACE --content-type application/javascript
      # For CSS files
      - aws s3 cp s3://your-bucket-name/dist/assets/ s3://your-bucket-name/dist/assets/ --recursive --exclude "*" --include "*.css" --metadata-directive REPLACE --content-type text/css
      # For HTML (index.html)
      - aws s3 cp s3://your-bucket-name/dist/index.html s3://your-bucket-name/dist/index.html --metadata-directive REPLACE --content-type text/html
      # Optional: For images/fonts (S3 often auto-detects, but add if needed)
      # - aws s3 cp s3://your-bucket-name/dist/assets/ s3://your-bucket-name/dist/assets/ --recursive --exclude "*" --include "*.png" --metadata-directive REPLACE --content-type image/png
      - echo "S3 sync complete!"
artifacts:
  files:
    - 'dist/**/*'
  discard-paths: yes
