version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies with npm ci..."
      - npm ci  # Installs exactly from package-lock.json
      - echo "Verifying Vite installation..."
      - ./node_modules/.bin/vite --version  # Quick check: should print Vite version
  build:
    commands:
      - echo "Building the app..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'  # Packages everything for deployment (e.g., to S3)
