version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies with npm ci..."
      - npm ci  
      - echo "Verifying Vite installation..."
      - ./node_modules/.bin/vite --version 
  build:
    commands:
      - echo "Building the app..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - 'dist/**/*'  

  discard-paths: yes 
